on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

# maven application, API URL from env
      - name: Cybeats SBOM Studio Action
        # uses: cybeats/sbom-studio-action@v1
        uses: REestwick/sbom-studio-action@reformat
        if: always()
        with:
          url:  ${{ secrets.APIURL }}
          filePath: cybeats-sbom-studio-plugin-cyclonedx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
