on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  
     
# Error:  maven application, API URL WRONG VALUE
      - name: v1.0.0
        uses: RobertHLiu/robert-action-test-release-and-tags@v1.0.0
        if: always()
      
      - name: v1.0.1
        uses: RobertHLiu/robert-action-test-release-and-tags@v1.0.1
        if: always()
      
      - name: v2.0.0
        uses: RobertHLiu/robert-action-test-release-and-tags@v2.0.0
        if: always()

      - name: v2.1.0
        uses: RobertHLiu/robert-action-test-release-and-tags@v2.1.0
        if: always()        

      - name: v1
        uses: RobertHLiu/robert-action-test-release-and-tags@v1
        if: always()

      - name: v2
        uses: RobertHLiu/robert-action-test-release-and-tags@v2
        if: always()
