on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
#      url: ${{secrets.APIURL}}
#      filePath: cybeats-sbom-studio-plugin-cyclonedx.json
#      secretAccessKey: ${{ secrets.SECRETKEY }}
#      accessKey: ${{ secrets.ACCESSKEY }}
#      subType: application
#      manufactureName: My Manufacturer
#      supplierName: My Supplier
#      threshold: Low
#      sbomQuality: 50
#      pkgType: maven
#      sbomComponenentName: Component Name
#      namespace: com.example.demo
      sbomComponentVersion: 1.0.0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        with:
          url: https://api.integ.inno.cybeats.com
          filePath: cybeats-sbom-studio-plugin-cyclonedx.json
          secretAccessKey: ${{ secrets.SECRETKEY }}
          accessKey: ${{ secrets.ACCESSKEY }}
          subType: application
#          manufactureName: Extreme! Lab, Indiana University
#          supplierName: Extreme! Lab, Indiana University
#         threshold: Critical
          sbomQuality: 50
          pkgType: maven
          sbomComponentName: Component Name
          namespace: com.example.demo
          sbomComponentVersion: ${{ env.sbomComponentVersion }}
