on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      INTEG_API_URL: 'https://api.integ.inno.cybeats.com'
#      filePath: cybeats-sbom-studio-plugin-cyclonedx.json
#      secretAccessKey: ${{ secrets.SECRETKEY }}
#      accessKey: ${{ secrets.ACCESSKEY }}
#      subType: application
#      manufactureName: My Manufacturer
#      supplierName: My Supplier
#      threshold: Low
#      sbomQuality: 50
#      pkgType: maven
#      sbomComponentName: Component Name
#      namespace: com.example.demo
#      sbomComponentVersion: 1.0.0
      APP_BASE_VER: '3.5'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

# maven application, API URL from env
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:  ${{ env.INTEG_API_URL }}
          filePath:   examples/application/cybeats-test-sbom-cli-non-root-component.json
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application     

# maven application, API URL from env
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:  ${{ env.INTEG_API_URL }}
          filePath:   examples/application/cybeats-test-sbom-cli-non-root-component.json
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application     
          pkgType: pypi
          sbomComponentName: test-sbom-cli-without-root-component
          sbomComponentVersion: ${{ env.APP_BASE_VER }}.${{ github.run_number }}.0

# maven application, API URL from env
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:  ${{ env.INTEG_API_URL }}
          filePath:   examples/application/cybeats-test-sbom-cli-non-root-component.json
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application     
          pkgType: pypi
          sbomComponentName: test-sbom-cli-without-root-component
          sbomComponentVersion: ${{ env.APP_BASE_VER }}.${{ github.run_number }}.1
          namespace: '@cybeats'