on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      INTEG_API_URL: 'https://api.integ.inno.cybeats.com'
#      filePath: cybeats-sbom-studio-plugin-cyclonedx.json
#      secretAccessKey: ${{ secrets.SECRETKEY }}
#      accessKey: ${{ secrets.ACCESSKEY }}
#      subType: application
#      manufactureName: My Manufacturer
#      supplierName: My Supplier
#      threshold: Low
#      sbomQuality: 50
#      pkgType: maven
#      sbomComponentName: Component Name
#      namespace: com.example.demo
#      sbomComponentVersion: 1.0.0
      APP_BASE_VER: '3.5'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

 # maven application, optional args -- Pass without threshold
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   "     ${{ secrets.APIURL }}    "
          filePath:  " cybeats-sbom-studio-plugin-cyclonedx.json   "
          secretAccessKey: "  ${{ secrets.SECRETKEY }}  " 
          accessKey: "  ${{ secrets.ACCESSKEY }}  "
          subType:  "  application  "
          manufactureName:  "  Cybeats   "
          supplierName:  " Cybeats       "
          sbomQuality:   50  
          pkgType:  " maven   "
          sbomComponentName: "  Example Component Name        "
          namespace:  "      com.example.demo  "
          sbomComponentVersion:  "   ${{ env.APP_BASE_VER }}.${{ github.run_number }}   "
 # maven application, optional args -- fail with Critical threshold (critical vulns present)
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   cybeats-sbom-studio-plugin-cyclonedx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application  
          manufactureName:   Cybeats  
          supplierName:   Cybeats
          threshold:   High
          sbomQuality:   50  
          pkgType:   maven  
          sbomComponentName:   Example Component Name      
          namespace:   com.example.demo  
          sbomComponentVersion:     ${{ env.APP_BASE_VER }}.${{ github.run_number }}         
 
# maven application, optional args -- actual quality 100, expect 100
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   cybeats-sbom-studio-plugin-cyclonedx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application  
          manufactureName:   Cybeats  
          supplierName:   Cybeats
          sbomQuality:   100
          pkgType:   maven  
          sbomComponentName:   Example Component Name      
          namespace:   com.example.demo  
          sbomComponentVersion:    1.0.0    
  
# golang application, optional args -- actual quality 90 ,expect 91
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   ./examples/application/docker-compose-2.1.34-cyclonedx-full-license-text.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:  application 
          pkgType:   golang
          sbomComponentName:   compose
          namespace:  github.com/docker 
          sbomComponentVersion:  1.0.0 
          sbomQuality: 90
# golang application, optional args -- actual quality 90, expect 90
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   ./examples/application/docker-compose-2.1.34-cyclonedx-full-license-text.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:  application 
          pkgType:   golang
          sbomComponentName:   compose
          namespace:  github.com/docker 
          sbomComponentVersion:  1.0.0
          sbomQuality: 0

# golang application, optional args -- quality meets expectation but vuln threshold doesn't -- has Critical vulns
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   ./examples/application/docker-compose-2.1.34-cyclonedx-full-license-text.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:  application 
          pkgType:   golang
          sbomComponentName:   compose
          namespace:  github.com/docker 
          sbomComponentVersion:  1.0.0-beta
          threshold: Low
          sbomQuality: 0                                                 

# golang application, optional args -- quality and threshold both fail
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:   ./examples/application/docker-compose-2.1.34-cyclonedx-full-license-text.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:  application 
          pkgType:   golang
          sbomComponentName:   compose
          namespace:  github.com/docker 
          sbomComponentVersion:  1.0.0-prerelease 
          threshold: Critical
          sbomQuality: 91


#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   Critical  
          sbomQuality:   50  
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9
#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   High 
          sbomQuality:   50  
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9

#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   Medium
          sbomQuality:   75  
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9  
          
#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   Low
          sbomQuality:   50  
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9
#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   Critical
          sbomQuality:   100
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9
#./spdx-examples/example9/spdx2.2/appbomination.spdx.json
      - name: Cybeats SBOM Studio Action
        uses: cybeats/sbom-studio-action@v1
        if: always()
        with:
          url:   ${{ secrets.APIURL }}  
          filePath:  ./spdx-examples/example9/spdx2.2/appbomination.spdx.json  
          secretAccessKey:   ${{ secrets.SECRETKEY }}  
          accessKey:   ${{ secrets.ACCESSKEY }}  
          subType:   application 
          threshold:   Low
          sbomQuality:   75  
          pkgType:   maven   
          sbomComponentName: appbomination 
          sbomComponentVersion:     8.8.5
          namespace: example9                         